### ISSUE TITLE
python not found in virtual environment

### ISSUE THREAD

**Issue by c30ra** [mfussenegger/nvim-dap-python#133]
On Windows, it can't find the python executable, cause it searches for python3. On Windows, usually there is no python3 executable installed.

I've temporary fixed it by rename the python executable from python.exe to python3.exe.

I'm doing something wrong or nvim-dap-python really expect a python3.exe on Windows??

**Comment by mfussenegger** [comment]
It doesn't look for a `python3.exe`

https://github.com/mfussenegger/nvim-dap-python/blob/66560f0ebddf96604f7037e1efad3ba6942761e6/lua/dap-python.lua#L55

https://github.com/mfussenegger/nvim-dap-python/blob/66560f0ebddf96604f7037e1efad3ba6942761e6/lua/dap-python.lua#L91

**Comment by c30ra** [comment]
Thanks for the the quick reply! Once I'm back home I'll double check my configuration. Today I managed to make it work only by renaming the executable. The error it gave me was something like: ENOENT: python3 file not found or something similar..

**Comment by c30ra** [comment]
I confirm that there is nothing on my nvim config that set python3

**Comment by mfussenegger** [comment]
Well, the only other `python3` occurrance is for the python that's used to run the `debugpy` adapter itself, which you can configure with the `setup` method.

See https://github.com/mfussenegger/nvim-dap-python/blob/66560f0ebddf96604f7037e1efad3ba6942761e6/lua/dap-python.lua#L182

Otherwise it has to come from your configuration.
