### ISSUE TITLE
Highlight and sign ignored

### ISSUE THREAD

**Issue by valentingregoire** [mfussenegger/nvim-dap-python#67]
When setting up the style of my breakpoints for `nvim-dap` like so:
```lua
vim.highlight.create("DapBreakpoint", { ctermbg = 0, guifg = "", guibg = "#4B1515" }, false)
vim.fn.sign_define(
	"DapBreakpoint",
	{ text = "", texthl = "DiagnosticSignError", linehl = "DapBreakpoint", numhl = "DapBreakpoint" }
)
```
My breakpoints are styled nicely. However, as soon as I activate `nvim-dap-python`, this style is ignored, and the initial style is applied (`B` sign and no line highlight). Any way to overcome this? I use the latest version of the plugin with Packer.

**Comment by mfussenegger** [comment]
nvim-dap-python doesn't do anything with the sign definitions. It pulls in `dap` itself which may override them if you're on 0.2. You can add a `require('dap')` before the `vim.fn.sign_define` call to avoid that. (And `vim.highlight.create` shouldn't be necessary)

In nvim-dap 0.3 you'll be able to define the signs up-front due to a change made in https://github.com/mfussenegger/nvim-dap/pull/664

**Comment by valentingregoire** [comment]
Defining the signs and highlights before importing (`require("nvim-dap-python")`) the module solved the problem. Just fyi, there is no tag 0.3 yet, it seems to be in 0.2 already.
